#!/usr/bin/python3
import json
import os
import sys

def migrate_volume(volume):
    return {
        'type': 'hostPath',
        'hostPathConfig': {
            'hostPath': volume['hostPath']
        },
    } if volume.get('hostPathEnabled', False) else {
        'type': 'ixVolume',
        'ixVolumeConfig': {
            'datasetName': volume['datasetName'],
        },
    }

def migrate_common_lib(values):
    delete_keys = [
        'enableResourceLimits', 'memLimit', 'cpuLimit', 'dnsConfig',
        'web_port', 'environmentVariables', 'timezone', 'password',
        'extraAppVolumeMounts', 'appVolumeMounts', 'dhcp', 'dhcp_start',
        'dhcp_end', 'dhcp_gateway', 'ownerUID', 'ownerGID',
    ]

    values.update({
        # Migrate Network
        'piholeNetwork': {
            'webPort': values['web_port'],
            'dhcp': {
                'enabled': values['dhcp'],
                'start': values.get('dhcp_start', ''),
                'end': values.get('dhcp_end', ''),
                'gateway': values.get('dhcp_gateway', ''),
            }
        },
        # Migrate Resources
        'resources': {
            'limits': {
                'cpu': values.get('cpuLimit', '4000m'),
                'memory': values.get('memLimit', '8Gi'),
            }
        },
        # Migrate DNS
        'podOptions': {
            'dnsConfig': {
                'options': [
                    {'name': opt['name'], 'value': opt['value']}
                    for opt in values.get('dnsConfig', {}).get('options', [])
                ]
            }
        },
        # Migrate Config
        'TZ': values['timezone'],
        'piholeConfig': {
            'webPassword': values['password'],
            'additionalEnvs': values.get('environmentVariables', []),
        },
        # Migrate Storage
        'piholeStorage': {
            'config': migrate_volume(values['appVolumeMounts']['config']),
            'dnsmasq': migrate_volume(values['appVolumeMounts']['dnsmasq']),
            'additionalStorages': [
                {
                    'type': 'hostPath',
                    'hostPathConfig': {'hostPath': e['hostPath']},
                    'mountPath': e['mountPath'],
                    'readOnly': e.get('readOnly', False),
                }
                for e in values.get('extraAppVolumeMounts', [])
            ],
        },
    })

    for k in delete_keys:
        values.pop(k, None)

    return values

def migrate(values):
    # If this missing, we have already migrated
    if not 'appVolumeMounts' in values.keys():
        # Handle typo for users that already gone through the migration
        if 'cache' in values['piholeStorage'].keys():
            values['piholeStorage']['dnsmasq'] = values['piholeStorage'].pop('cache')

        return values

    return migrate_common_lib(values)


if __name__ == '__main__':
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], 'r') as f:
            print(json.dumps(migrate(json.loads(f.read()))))
