#!/usr/bin/python3
import json
import os
import sys


def migrate(values):
    storageKey = 'mumbleStorage'
    storages = ['data']


    for storage in storages:
        check_val = values.get(storageKey, {}).get(storage, {})
        if not isinstance(check_val, dict) or not check_val or check_val.get('type', 'hostPath') == 'hostPath':
            continue

        values[storageKey][storage] = {key: value for key, value in check_val.items() if key != 'hostPath'}


    return values


if __name__ == '__main__':
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], 'r') as f:
            print(json.dumps(migrate(json.loads(f.read()))))
